# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# ----------
# Dockerfile for Website Scraper MCP Server
# ----------

# Use official Node.js LTS Alpine image
FROM node:lts-alpine

# Create app directory
WORKDIR /app

# Install app dependencies
# Copy package.json and package-lock.json first for caching
COPY package.json package-lock.json tsconfig.json ./

# Install all dependencies (including dev for build)
RUN npm install

# Copy the rest of the source code
COPY . .

# Build the TypeScript source
RUN npm run build

# The MCP server communicates over stdio, so no ports are exposed
# Define the default command to start the MCP server
CMD ["node", "build/index.js"]
